### ISSUE TITLE
go适合写 restful api 吗?

### ISSUE THREAD

**Issue by vmvz** [bonfy/go-mega#1]
现在很多项目前后端分离了吧,go适合写 restful api 吗?

**Comment by bonfy** [comment]
restful api 和语言无关，Go、Python 啥语言都可以写

Go 比较好的地方是 用Go写可以轻松获取到不错的性能。

具体写法可以看下: [https://github.com/bonfy/go-tips/blob/master/package/01-render/main.go](https://github.com/bonfy/go-tips/blob/master/package/01-render/main.go)
