### ISSUE TITLE
关于第八章、第九章例子前端页面无法完整显示的问题

### ISSUE THREAD

**Issue by AaronWharton** [bonfy/go-mega#4]
Hello，作者您好！我在学习您这个项目过程中自己仿照了一个[项目](https://github.com/AaronWharton/ss)（代码基本一样，结构稍有改动）。在第八章第九章的例子中我使用您项目中的前段代码，发现在渲染的时候没有出现 `follow` 、 `old` 等关注、分页的按钮。为了避免是自己的问题，我做了以下检查：
- 前端代码有误导致渲染失败？直接复制原项目代码后还是一样的结果。
- 是不是没有把数据写入数据库？查询后发现数据插入成功。

后来想可能是兼容问题？（前端一点都不了解，瞎猜的）直接在 url 后面加类似于 `?page=2` 这样的参数，发现能成功显示分页的内容。

结果如下图所示，第一张是不加 `page` 参数的截图，第二张是加了 `page` 参数的截图，第三张是 `follow` 和 `unfollow` 按钮无法正常显示出来的页面：

![image](https://user-images.githubusercontent.com/19624442/50142006-dec82080-02e3-11e9-8dbe-97a3b686fc7b.png)
![image](https://user-images.githubusercontent.com/19624442/50142096-2f3f7e00-02e4-11e9-9374-bbe1c35dc61c.png)
![image](https://user-images.githubusercontent.com/19624442/50142242-96f5c900-02e4-11e9-9354-b6e1f4dbbcf6.png)

综上，想请教一下作者怎么修改才能完整地显示您教程上面的前端页面？十分感谢！

**Comment by bonfy** [comment]
@AaronWharton 

follow 和  unfollow 按钮的逻辑 

```html
                {{if .Editable}}
                    <p><a href="/profile_edit">Edit your profile</a></p>
                {{else}}
                    {{if .IsFollow}}
                        <p><a href="/unfollow/{{.ProfileUser.Username}}">Unfollow</a></p>
                    {{else}}
                        <p><a href="/follow/{{.ProfileUser.Username}}">Follow</a></p>
                    {{end}}
                {{end}}
```

分页逻辑 

```html
     {{ if gt .PrevPage 0 }}
        <a href="/user/{{.ProfileUser.Username}}?page={{.PrevPage}}">Newer posts</a>
    {{ end }}
    {{ if gt .NextPage 0 }}
        <a href="/user/{{.ProfileUser.Username}}?page={{.NextPage}}">Older posts</a>
    {{ end }}
```

现在还有这个问题么?

**Comment by AaronWharton** [comment]
html 代码是一样的，现在是判断了 `if .Editable` 后只能显示 Edit your profile 这个按钮，后面的判断看起来就不执行了：

![image](https://user-images.githubusercontent.com/19624442/50196083-c2c48d80-037c-11e9-84e0-9fe407e333e2.png)

**Comment by bonfy** [comment]
@AaronWharton 有 Edit your profile 说明你登录的用户 就是  allen，对于自己的profile 是 修改功能，如果你用 allen 的用户 查看 aaron 的profile，就会显示 follow 和 unfollow

**Comment by AaronWharton** [comment]
是的，问题就是用 allen 查看 aaron 不会显示 follow 和 unfollow 的按钮。我觉得应该是我命名改了导致页面不显示的，不过跟项目关系不大，不影响学习。我再研究研究，谢谢了！
