### ISSUE TITLE
第二章 Template Basic 中 templates 路径位置问题

### ISSUE THREAD

**Issue by tigren** [bonfy/go-mega#5]
第二章提到的 templates 没有说明在哪里创建
```shell
$ mkdir templates
```
比如我是在 `main.go` 所在的目录创建的，这样的话直接运行会报错，需要把路径改成相对路径:

```go
tpl, _ := template.ParseFiles("./templates/index.html")
```

**Comment by bonfy** [comment]
@tigren 

你好，每章的代码 在 README 中都提供了链接

第二章的是 https://github.com/bonfy/go-mega-code/tree/02-Template

希望能解决你的问题

**Comment by tigren** [comment]
@bonfy 谢谢，可以运行了
