### ISSUE TITLE
关于第二章中struct属性名和template{{属性名}}的问题

### ISSUE THREAD

**Issue by starhwz** [bonfy/go-mega#6]
```go
//struct User 的属性 username小写
type User struct {
	username string
}
user := User{username: "sizz"}
// template中也是小写
<h1>Hello,{{.username}}!</h1>
```
之后页面如下：
![QQ截图20190515165329](https://user-images.githubusercontent.com/20556539/57762478-29828300-7732-11e9-895d-fe432d2a9f8b.png)

我的全部代码贴上：
![QQ截图20190515165617](https://user-images.githubusercontent.com/20556539/57762602-60f12f80-7732-11e9-8bfc-67fd4c3066a3.png)

将username换成Username之后就可以出现正常结果。想请问下，为什么首字母一定要大写。
谢谢。

**Comment by bonfy** [comment]
@starhwz

Go 是根据首字母的大小写来确定可以访问的权限。无论是方法名、常量、变量名还是结构体的名称，如果首字母大写，则可以被其他的包访问；如果首字母小写，则只能在本包中使用。

你可以把 小写开头的属性 当作 私有变量， Template 就没法访问到了，这么理解

**Comment by starhwz** [comment]
> @starhwz
> 
> Go 是根据首字母的大小写来确定可以访问的权限。无论是方法名、常量、变量名还是结构体的名称，如果首字母大写，则可以被其他的包访问；如果首字母小写，则只能在本包中使用。
> 
> 你可以把 小写开头的属性 当作 私有变量， Template 就没法访问到了，这么理解

谢谢，之前没系统的了解。非常感谢您的回答。
